Howitworks1
Nikolaus-B/veggieboost-team-8 pull request #3
Opened 2023-07-01 16:47 UTC by Serguk20

2023-07-01 20:09 UTC, Nikolaus-B requested changes
Є недороблення, картинки тільки десктопні, треба робити через тег picture, також контент зжимається до 320px там можна на картинку дати max-width, і ще потрібно на секцію дати id для того щоб можна було на нього перейти з хедера

2023-07-02 15:28 UTC, Nikolaus-B requested changes
https://www.loom.com/share/f6d5f795562c472c89702ac8796461c6

2023-07-02 17:09 UTC, Nikolaus-B requested changes
видали свої картинки і все готово)

2023-07-03 14:39 UTC, Nikolaus-B approved these changes

2023-07-03 16:39 UTC, yuyaruchyk approved these changes

2023-07-03 17:00 UTC, merged