Footer
Nikolaus-B/veggieboost-team-8 pull request #6
Opened 2023-07-03 08:27 UTC by Andrey-hdsh

пофіксив марджін на списку адреси та контактів + добавив id посилання на секції 
Дякую , чекаю на  feedback від ревьюєрів !

2023-07-03 11:10 UTC, Nikolaus-B requested changes
https://www.loom.com/share/c190b8b1567d420ea646dc3c750394c1

2023-07-03 15:15 UTC, yuyaruchyk approved these changes

2023-07-03 15:39 UTC, iryna-popkova approved these changes

2023-07-03 20:15 UTC, Nikolaus-B requested changes
https://www.loom.com/share/9d584aa225194e81aa2a8aa3a5d12c24

2023-07-04 13:29 UTC, Nikolaus-B approved these changes

2023-07-04 13:44 UTC, merged