Секція - we-will-call-you
Nikolaus-B/veggieboost-team-8 pull request #8
Opened 2023-07-03 16:21 UTC by SergeyReznickyy

2023-07-03 16:50 UTC, Nikolaus-B requested changes
https://www.loom.com/share/2339754b8a3f4740b941a829c6c6dbd5

2023-07-03 17:11 UTC, Nikolaus-B approved these changes

2023-07-03 20:21 UTC, Nikolaus-B approved these changes

2023-07-04 13:36 UTC, YVolkov404 approved these changes
_! Загалом все гаразд

2023-07-04 13:43 UTC, merged