Hero
Nikolaus-B/veggieboost-team-8 pull request #9
Opened 2023-07-03 18:02 UTC by YVolkov404

2023-07-03 20:34 UTC, Nikolaus-B requested changes
https://www.loom.com/share/b549526e26ce4ef2bc77fec9dc25d36a

2023-07-03 21:54 UTC, YVolkov404 commented
_! Дякую за ревью > начебто все пофіксив

2023-07-04 13:22 UTC, Nikolaus-B requested changes
https://www.loom.com/share/01f219cf759b463597a3c2227de0906c

2023-07-04 14:24 UTC, YVolkov404 commented
_! Дякую за ревью > пофіксив

2023-07-04 15:07 UTC, Nikolaus-B approved these changes

2023-07-04 17:49 UTC, merged